### ISSUE TITLE
Some textures not loaded into game

### ISSUE THREAD

**Issue by floydGG** [three5media/mfhu-hd-retexture#1]
Pokke Village dirt road , Guild Hall and some areas in other map not loaded.

**Comment by floydGG** [comment]
Looks like u forgot to rename the textures in textures.ini ? :D
I just rename it just like the png files.
All good now 
![image](https://user-images.githubusercontent.com/53382214/171585479-be5568e6-1276-4e69-b3e9-7404ef11c1cb.png)

**Comment by three5media** [comment]
Sorry about that.  I decided to go back to the more original look with those textures.  The non-lettered ones are upscaled, they just don't look as clean as the ones I created.   I just wanted both options available.   Thanks for noticing the fix.

**Comment by floydGG** [comment]
> Sorry about that. I decided to go back to the more original look with those textures. The non-lettered ones are upscaled, they just don't look as clean as the ones I created. I just wanted both options available. Thanks for noticing the fix.

Ah i see, after i play along with the alternative texture, i still prefer the old ones :D 
Awesome work man, hope people on ppsspp forum would appreciate your post more.

**Comment by romatthe** [comment]
Sorry to comment on this ancient post, but @three5media, you might want to update the screenshots in the main readme. I almost decided not to download this texture pack because I thought the new village ground textures showcased in the screenshots looked really bad. 

I don't mean to insult your work at all, just wanted to point out that some people might have the same reaction even though the screenshot isn't representative anymore.

Definitely a great decision to stick more to the original style, I appreciate your work!
